SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD 
    FROM APPOINTMENT A, DOCTOR D, PATIENT P 
    WHERE D.DR_ID=A.MDDR_ID AND A.PT_NO = P.PT_NO AND DATE(A.APNT_YMD) = "2022-04-13" AND A.APNT_CNCL_YN = "N" 
    ORDER BY A.APNT_YMD ASC