SELECT REST_REVIEW.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE 
FROM REST_REVIEW 
LEFT JOIN REST_INFO ON REST_INFO.REST_ID = REST_REVIEW.REST_ID 
WHERE ADDRESS LIKE "¼­¿ï%" GROUP BY REST_REVIEW.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC