(1)
SELECT a.FOOD_TYPE, a.REST_ID, a.REST_NAME, a.FAVORITES FROM REST_INFO a JOIN ( SELECT MAX(FAVORITES) as 'MAX_F' FROM REST_INFO GROUP BY FOOD_TYPE ) b on (a.FAVORITES = b.MAX_F) GROUP BY FOOD_TYPE ORDER BY FOOD_TYPE DESC

(2)
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES 
FROM REST_INFO
where (FOOD_TYPE, FAVORITES)
IN (SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC