SELECT TEMP.AUTHOR_ID, TEMP.AUTHOR_NAME, TEMP.CATEGORY, SUM(TEMP.TOTAL_SALES) AS TOTAL_SALES 
    FROM (
        SELECT BOOK.BOOK_ID, BOOK.AUTHOR_ID, AUTHOR_NAME, CATEGORY, (BOOK.PRICE * SALES) AS TOTAL_SALES 
            FROM BOOK, AUTHOR, BOOK_SALES 
            WHERE BOOK.BOOK_ID = BOOK_SALES.BOOK_ID 
                AND AUTHOR.AUTHOR_ID = BOOK.AUTHOR_ID 
                AND YEAR(SALES_DATE) = "2022" 
                AND MONTH(SALES_DATE) = "1" 
            GROUP BY BOOK_ID, SALES_DATE 
    ) TEMP
    GROUP BY TEMP.AUTHOR_ID, CATEGORY 
    ORDER BY TEMP.AUTHOR_ID ASC, TEMP.CATEGORY DESC