SELECT A.CATEGORY, A.PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
RIGHT JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE 
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN ("과자", "국", "김치", "식용유")
    GROUP BY CATEGORY
    ) B
    ON A.CATEGORY = B.CATEGORY AND A.PRICE=B.MAX_PRICE
ORDER BY PRICE DESC

# 막 때려넣은 정답
SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME FROM FOOD_PRODUCT WHERE (CATEGORY, PRICE) IN (
 (SELECT CATEGORY, MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY HAVING CATEGORY = "식용유"), 
 (SELECT CATEGORY, MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY HAVING CATEGORY = "과자"),
 (SELECT CATEGORY, MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY HAVING CATEGORY = "국"),
 (SELECT CATEGORY, MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY HAVING CATEGORY = "김치")) ORDER BY MAX_PRICE DESC