SELECT TEMP1.MEMBER_NAME, TEMP1.REVIEW_TEXT, date_format(TEMP1.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE FROM(
    SELECT REST.MEMBER_ID, MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE FROM REST_REVIEW AS REST 
    JOIN MEMBER_PROFILE AS MEM ON REST.MEMBER_ID = MEM.MEMBER_ID
    ) TEMP1
JOIN 
(SELECT MEMBER_ID, COUNT(MEMBER_ID) AS COUNT_ID FROM REST_REVIEW 
 GROUP BY MEMBER_ID HAVING COUNT_ID = (
    SELECT MAX(COUNT_ID) FROM (
        SELECT COUNT(MEMBER_ID) AS COUNT_ID FROM REST_REVIEW 
        GROUP BY MEMBER_ID) 
    TEMP2)
) TEMP3 ON TEMP1.MEMBER_ID = TEMP3.MEMBER_ID ORDER BY REVIEW_DATE, REVIEW_TEXT ASC